name: Build and push Docker image to Ucloud and deploy to Product server

on:
  push:
    branches:
      - master
permissions:
  contents: read
  actions: read

jobs:
  build-and-push:
    name: build-and-push
    uses: unnoo/actions-template/.github/workflows/master.yaml@master
    secrets: inherit
    with:
      service_name: starry-www
      namespace: default
      deploy_script: |
        kubectl set image deployment starry-sg nginx=uhub.service.ucloud.cn/unnoo/starry-www:$SHORT_SHA
        kubectl annotate deployment starry-sg kubernetes.io/change-cause="Rolling update to $SHORT_SHA" --overwrite

